power <- read.table("/Users/antoniosi/personal/Courses/Exploratory/Project1/household_power_consumption.txt", header = TRUE, sep=";", na.strings="?")
power$Date <- as.Date(power$Date, format="%d/%m/%Y")
powerRange <- subset(power, power$Date >= as.Date("01/02/2007", "%d/%m/%Y") & power$Date <= as.Date("02/02/2007", "%d/%m/%Y"))
powerRange$timestamp <- paste(powerRange$Date, powerRange$Time)
powerRange$timestamp <- strptime(powerRange$timestamp, format="%Y-%m-%d %H:%M:%S")
par(mfrow=c(2,2), oma=c(0,0,2,0), mar=c(3,4,2,1))
plot(powerRange$timestamp, powerRange$Global_active_power, type="l", ylab="Global Active Power", xlab="", ylim=c(0,6), cex.axis=0.7, cex.lab=0.7)
plot(powerRange$timestamp, powerRange$Voltage, type="l", ylab="Voltage", xlab="datetime", cex.axis=0.7, cex.lab=0.7)
plot(powerRange$timestamp, powerRange$Sub_metering_1, type="l", ylab="Energy sub metering", xlab="", col="black", ylim=c(0,40), cex.axis=0.7, cex.lab=0.7)
par(new=T)
plot(powerRange$timestamp, powerRange$Sub_metering_2, type="l", ylab="Energy sub metering", xlab="", col="red", ylim=c(0,40), cex.axis=0.7, cex.lab=0.7)
par(new=T)
plot(powerRange$timestamp, powerRange$Sub_metering_3, type="l", ylab="Energy sub metering", xlab="", col="blue", ylim=c(0,40), cex.axis=0.7, cex.lab=0.7)
legend("topright", lty=c(1,1,1), col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), cex=0.5)
plot(powerRange$timestamp, powerRange$Global_reactive_power, type="l", ylab="Global_reactive_power", xlab="datetime", ylim=c(0,0.5), cex.axis=0.7, cex.lab=0.7)
dev.copy(png, file="plot4.png")
dev.off()
